name: Deployment Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: /home/seguser/hng/fastapi-book-project

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: /home/seguser/hng/fastapi-book-project

      - name: Deploy Application
        run: |
          sudo systemctl restart fastapi-app
          sudo systemctl reload nginx

      - name: Verify Services
        run: |
          if ! systemctl is-active --quiet fastapi-app; then
          echo "FastAPI service is not running!"
          exit 1
          fi
          if ! systemctl is-active --quiet nginx; then
          echo "Nginx service is not running!"
          exit 1
          fi
