name: Deployment Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Application
        run: |
          sudo systemctl restart fastapi-app
          sudo systemctl reload nginx
